#93 Fix disable_dialog_boxes
square/pylink pull request #96
Opened 2021-04-10 09:53 UTC by kettenbach-it

2021-04-10 10:07 UTC, kettenbach-it commented
@hkpeprah Please approve!

2021-04-12 14:48 UTC, hkpeprah requested changes
Sorry about the late review.  Only thing that needs changing is to re-enable the flash dialog popups when `enable_dialog_boxes()` is called.  Otherwise LGTM.

2021-04-12 14:48 UTC, hkpeprah commented on pylink/jlink.py
> +        self.exec_command("HideDeviceSelection = 0")
I think you'll also need to re-enable the info windows: `EnableInfoWinFlashBPs`, and `EnableInfoWinFlashDL`.

2021-04-12 15:59 UTC, kettenbach-it commented
@hkpeprah Please approve!

2021-04-12 20:37 UTC, hkpeprah approved these changes
Sorry for the delay here.  Just tested out locally, and LGTM.  Will merge and cut a minor release later today.

2021-04-12 20:38 UTC, merged

2021-04-12 20:52 UTC, hkpeprah commented
Fix should be present in `v0.10.0`.